[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RLIntro = "02c1da58-b9a1-11e8-0212-f9611b8fe936"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
